# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=40)),
                ('stoken', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
