# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20180413_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerMac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=30)),
                ('flower_other_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerMaxMinHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=30)),
                ('max_humidity', models.IntegerField()),
                ('min_humidity', models.IntegerField()),
            ],
        ),
    ]
