# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_flowermac_flowermaxminhumidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowermac',
            name='mac',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
