# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_flowermac_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
