# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mac', models.CharField(max_length=30)),
            ],
        ),
    ]
