# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_usermac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermac',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
